### ISSUE TITLE
build:prpl-server error on Windows 10

### ISSUE THREAD

**Issue by AiMingQi** [Polymer/pwa-starter-kit#118] opened 2018-05-18 15:26 UTC
In package.json there is a Unix only command that won't run on Windows 10. 

rm -rf 

`"build:prpl-server": "polymer build --auto-base-path && rm -rf server/build && mv build server/ && renamer --find node_modules --replace node_assets 'server/build/**' && replace node_modules node_assets server/build -r -s"`

**Comment by Dabolus** [comment] 2018-05-18 15:45
Duplicate of #95, this is going to be fixed as soon as #111 gets merged

**Closed** 2018-05-18 15:46 UTC
