### ISSUE TITLE
Integration test errors

### ISSUE THREAD

**Issue by potens1** [Polymer/pwa-starter-kit#114] opened 2018-05-16 17:52 UTC
When I try to run the integration tests from a fresh clone, I get errors at the end:

```(pwa-starter-kit) ~/d/p/my-app ❯❯❯ npm run test:integration                                                                                                                                  ⏎

> pwa-starter-kit@0.8.0 test:integration /home/nic/dev/pwa-starter-kit/my-app
> mocha test/integration --timeout=10000



  routing tests
    ✓ the page selector switches pages (1764ms)
    ✓ the page selector switches pages in a different way (946ms)

  👀 page screenshots are correct
    wide screen
📸 wide/index.png => 61678 bytes, 0.2072707746118374% different
      1) /index.html
📸 wide/view1.png => 61678 bytes, 0.2072707746118374% different
      2) /view1
📸 wide/view2.png => 59020 bytes, 0.22544875585299656% different
      3) /view2
📸 wide/view3.png => 59593 bytes, 0.1876301971788609% different
      4) /view3
📸 wide/batmanNotAView.png => 26058 bytes, 0.04283317418893817% different
      5) /404
    narrow screen
📸 narrow/index.png => 70159 bytes, 0.4054856996033467% different
      6) /index.html
📸 narrow/view1.png => 70159 bytes, 0.4054856996033467% different
      7) /view1
📸 narrow/view2.png => 58060 bytes, 0.4147195323665912% different
      8) /view2
📸 narrow/view3.png => 59637 bytes, 0.35449888391064865% different
      9) /view3
📸 narrow/batmanNotAView.png => 19305 bytes, 0.07186330715742481% different
      10) /404


  2 passing (16s)
  10 failing

  1) 👀 page screenshots are correct
       wide screen
         /index.html:

      number of different pixels
      + expected - actual

      -992
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  2) 👀 page screenshots are correct
       wide screen
         /view1:

      number of different pixels
      + expected - actual

      -992
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  3) 👀 page screenshots are correct
       wide screen
         /view2:

      number of different pixels
      + expected - actual

      -1079
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  4) 👀 page screenshots are correct
       wide screen
         /view3:

      number of different pixels
      + expected - actual

      -898
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  5) 👀 page screenshots are correct
       wide screen
         /404:

      number of different pixels
      + expected - actual

      -205
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  6) 👀 page screenshots are correct
       narrow screen
         /index.html:

      number of different pixels
      + expected - actual

      -1010
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  7) 👀 page screenshots are correct
       narrow screen
         /view1:

      number of different pixels
      + expected - actual

      -1010
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  8) 👀 page screenshots are correct
       narrow screen
         /view2:

      number of different pixels
      + expected - actual

      -1033
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  9) 👀 page screenshots are correct
       narrow screen
         /view3:

      number of different pixels
      + expected - actual

      -883
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)

  10) 👀 page screenshots are correct
       narrow screen
         /404:

      number of different pixels
      + expected - actual

      -179
      +0

      at exports.PNG.doneReading (test/integration/visual.js:143:59)
      at exports.PNG.<anonymous> (node_modules/pngjs/lib/png.js:37:10)
      at module.exports.ParserAsync._complete (node_modules/pngjs/lib/parser-async.js:153:8)
      at module.exports.complete (node_modules/pngjs/lib/filter-parse-async.js:19:12)
      at module.exports.Filter._reverseFilterLine (node_modules/pngjs/lib/filter-parse.js:169:10)
      at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
      at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
      at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
      at Inflate.<anonymous> (node_modules/pngjs/lib/parser-async.js:94:9)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at Inflate.Readable.push (_stream_readable.js:218:10)
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)



npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! pwa-starter-kit@0.8.0 test:integration: `mocha test/integration --timeout=10000`
npm ERR! Exit status 10
npm ERR!
npm ERR! Failed at the pwa-starter-kit@0.8.0 test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nic/.npm/_logs/2018-05-16T17_24_14_312Z-debug.log
```

With the debug log:

```
(pwa-starter-kit) ~/d/p/my-app ❯❯❯ cat /home/nic/.npm/_logs/2018-05-16T17_24_14_312Z-debug.log                                                                                               ⏎
0 info it worked if it ends with ok
1 verbose cli [ '/home/nic/.virtualenvs/pwa-starter-kit/bin/node',
1 verbose cli   '/home/nic/.virtualenvs/pwa-starter-kit/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:integration' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'pretest:integration',
4 verbose run-script   'test:integration',
4 verbose run-script   'posttest:integration' ]
5 info lifecycle pwa-starter-kit@0.8.0~pretest:integration: pwa-starter-kit@0.8.0
6 info lifecycle pwa-starter-kit@0.8.0~test:integration: pwa-starter-kit@0.8.0
7 verbose lifecycle pwa-starter-kit@0.8.0~test:integration: unsafe-perm in lifecycle true
8 verbose lifecycle pwa-starter-kit@0.8.0~test:integration: PATH: /home/nic/.virtualenvs/pwa-starter-kit/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/nic/dev/pwa-starter-kit/my-app/node_modules/.bin:/home/nic/.virtualenvs/pwa-starter-kit/bin:/usr/lib/hardening-wrapper/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/opt/marytts/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle pwa-starter-kit@0.8.0~test:integration: CWD: /home/nic/dev/pwa-starter-kit/my-app
10 silly lifecycle pwa-starter-kit@0.8.0~test:integration: Args: [ '-c', 'mocha test/integration --timeout=10000' ]
11 silly lifecycle pwa-starter-kit@0.8.0~test:integration: Returned: code: 10  signal: null
12 info lifecycle pwa-starter-kit@0.8.0~test:integration: Failed to exec test:integration script
13 verbose stack Error: pwa-starter-kit@0.8.0 test:integration: `mocha test/integration --timeout=10000`
13 verbose stack Exit status 10
13 verbose stack     at EventEmitter.<anonymous> (/home/nic/.virtualenvs/pwa-starter-kit/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/nic/.virtualenvs/pwa-starter-kit/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid pwa-starter-kit@0.8.0
15 verbose cwd /home/nic/dev/pwa-starter-kit/my-app
16 verbose Linux 4.16.8-1-ARCH
17 verbose argv "/home/nic/.virtualenvs/pwa-starter-kit/bin/node" "/home/nic/.virtualenvs/pwa-starter-kit/bin/npm" "run" "test:integration"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 10
22 error pwa-starter-kit@0.8.0 test:integration: `mocha test/integration --timeout=10000`
22 error Exit status 10
23 error Failed at the pwa-starter-kit@0.8.0 test:integration script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 10, true ]
```

it seems the value of numDiffPixels is `['', '']`

The version of picelmatch I have is
```
pixelmatch@4.0.2
```
PS: the files are generated:
```
(pwa-starter-kit) ~/d/p/my-app ❯❯❯ find test/integration -name "*png"|xargs file
test/integration/screenshots-baseline/narrow/batmanNotAView.png: PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/narrow/index.png:          PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/narrow/view1.png:          PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/narrow/view2.png:          PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/narrow/view3.png:          PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/wide/batmanNotAView.png:   PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/wide/index.png:            PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/wide/view1.png:            PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/wide/view2.png:            PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-baseline/wide/view3.png:            PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/wide/index.png:             PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/wide/view1.png:             PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/wide/view2.png:             PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/wide/view3.png:             PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/wide/batmanNotAView.png:    PNG image data, 800 x 600, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/narrow/index.png:           PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/narrow/view1.png:           PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/narrow/view2.png:           PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/narrow/view3.png:           PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
test/integration/screenshots-current/narrow/batmanNotAView.png:  PNG image data, 375 x 667, 8-bit/color RGBA, non-interlaced
(pwa-starter-kit) ~/d/p/my-app ❯❯❯
```

**Comment by notwaldorf** [comment] 2018-05-16 19:29
Are you running the tests on a not MacOS machine? There's a [note](https://github.com/Polymer/pwa-starter-kit/wiki/7.-Application-testing#screenshot-testing) about this in the docs, where the tl; dr is: screenshot testing only works if you test on a machine similar to that where the baselines are generated (because font metrics are not the same across platforms). If the tests fail out of the box, you should probably regenerate them for your local copy of the app.

**Comment by potens1** [comment] 2018-05-17 17:53
Hi,
Indeed, I'm not on a MacOS machine, I did not had seen the note (sorry). I'm not able to regenerate to screenshots 

```
(pwa-starter-kit) ~/d/p/my-app ❯❯❯ node_modules/mocha/bin/mocha test/integration/screenshots-baseline/regenerate.js


  🎁 regenerate screenshots
wide...
    1) did it


  0 passing (3s)
  1 failing

  1) 🎁 regenerate screenshots
       did it:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/nic/dev/pwa-starter-kit/my-app/test/integration/screenshots-baseline/regenerate.js)
```
But when I copy the screenshots generated by the tests to the baseline, the tests passes and there no error anymore.

I was a bit surprised by the format of the output when tests are failing (and more by the 
```
      at Inflate.Transform.push (_stream_transform.js:146:32)
      at Zlib.processCallback (zlib.js:556:10)



npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! pwa-starter-kit@0.8.0 test:integration: `mocha test/integration --timeout=10000`
npm ERR! Exit status 10
```
it was more looking like a crash to me, I'm not used to mocha)

Thank you

**Comment by notwaldorf** [comment] 2018-05-17 18:09
can you try running the regenerate again? sometimes it fails randomly, but works on the second try

**Comment by potens1** [comment] 2018-05-17 23:08
Retried lot of time and it did not change the result, but:
```
(pwa-starter-kit) ~/d/p/my-app ❯❯❯ node_modules/mocha/bin/mocha test/integration/screenshots-baseline/regenerate.js --timeout=10000                                                          ⏎


  🎁 regenerate screenshots
wide...
narrow...
    ✓ did it (9395ms)


  1 passing (10s)
```
Then, some screenshots are generated, but they are not good.
![view1](https://user-images.githubusercontent.com/3988571/40207680-14aa1a02-5a36-11e8-86f0-299811d5880a.png)

Only the batmanNotAView (both), the view2 (narrow) and index (wide) are fully loaded before screenshot when regenerating (always the same are well created, and always the same are failing, it seems)

Increasing the timeout further did not change anything also, the needed time is almost always the same (9.3s :-( )

**Comment by notwaldorf** [comment] 2018-06-20 18:40
Honestly, not sure what's going on here. I can't reproduce this, so I don't know where to go with this. It sounds like it's some form of timing error, where the screenshot is taken before the page is loaded, but I don't know why that would only happen on your computer.

**Comment by notwaldorf** [comment] 2018-06-20 18:41
I've reproduced it in the past on a different project -- let me try reproing it there and get back to you.

**Comment by notwaldorf** [comment] 2018-06-21 00:09
Closing this since I don't know how to repro, but please reopen if you've got more repro steps.

**Closed by notwaldorf** 2018-06-21 00:09 UTC
Labels: pending-response

**Comment by irishandyb** [comment] 2018-08-02 08:52
Hi,

I ran into the same issue. There definitely is a timing issue between the page loads and the screenshots.

```
      await page.goto(`http://127.0.0.1:4444/view${i}`);
      await page.screenshot({path: `${baselineDir}/${prefix}/view${i}.png`});
```

I'm new to all this but perhaps the `page.goto` is resolving once the navigation is completed but before the new page is dynamically routed/loaded.

Either way, I worked around the issue by artificially introducing a delay within puppeteer.

```
--- a/test/integration/screenshots-baseline/regenerate.js
+++ b/test/integration/screenshots-baseline/regenerate.js
@@ -36,7 +36,7 @@ describe('🎁 regenerate screenshots', function() {
   after((done) => polyserve.close(done));
 
   beforeEach(async function() {
-    browser = await puppeteer.launch();
+    browser = await puppeteer.launch({headless: false, slowMo: 100});
     page = await browser.newPage();
   });
```

The headless=false is optional but the slowMo=100 masks the timing issue.

Not a great solution but a workaround nonetheless.

**Comment by cinmay** [comment] 2019-02-26 21:26
I can confirm the solutions provided by @irishandyb works. I also added 10 seconds to moca in package.json to avoid timeouts. 
mocha test/integration/screenshots-baseline/regenerate.js --timeout=25000
