### ISSUE TITLE
Dynamic import breaks build

### ISSUE THREAD

**Issue by kr05** [Polymer/pwa-starter-kit#231] opened 2018-09-14 03:52 UTC
I'm not exactly sure where to post this, so if this is the incorrect place I would appreciate some pointers as to where that would be. I'm currently using pwa-starter-kit as a base for my web app. I've had no issues, until for no apparent reason I started running into some build issues. I spent two days debugging, only to find out that this innocuous looking piece of code was the cause of all my troubles:

```javascript
  _onEditPatient(patient) {
    console.log('on edit patient event:', patient);
    import('./dialogs/create-patient/create-patient.js').then(response => {
      var editPatientEl = this.shadowRoot.querySelector('#createPatient');
      editPatientEl.setAttribute('opened', true);
      editPatientEl.patientName = patient.name;
      editPatientEl.patientEmail = patient.email;
      editPatientEl.patientPhone = patient.phone;
      editPatientEl.patientAddress = patient.address;
      editPatientEl.patientDob = patient.dob.original;
      editPatientEl.image = patient.image;
      editPatientEl.pid = patient.__id__;
      editPatientEl.editState = true;
    });
  }
```

Which causes the following error after building:
![image](https://user-images.githubusercontent.com/11833744/45527441-73286180-b790-11e8-81ac-5f69c9c64d02.png)

This is the error after setting the "transformModulesToAmd" inside my polymer.json to false:
![image](https://user-images.githubusercontent.com/11833744/45527488-c1d5fb80-b790-11e8-8d79-f5cd877cab92.png)

I have very similar import statements all over my app, and none have caused me any problems...but for some reason this particular one does. 

It also isn't a problem with the element itself. This particular element has two uses: creating and editing a patient. Here's the code that lazy loads the same element, but for the "create" use case...

```javascript
  _onCreateClick(e) {
    console.log('on create click:', e)
    switch (this._page) {
      case 'patients':
        import('./dialogs/create-patient/create-patient.js').then(response => {
          this.shadowRoot.querySelector('#createPatient').setAttribute('opened', true);
        });
        break;
        break;
    }
  }
```
...which works perfectly fine. 

Interestingly, importing the element directly introduced a new error:
![image](https://user-images.githubusercontent.com/11833744/45527967-1bd7c080-b793-11e8-8213-bebfca4132f4.png)

Additionally, the code works before building it. This leaves the build process as the most probable culprit. I'm using the polymer-cli build command. Here's my polymer.json:
```json
{
  "entrypoint": "index.html",
  "shell": "src/my-app.js",
  "sources": [
    "images/**/*"
  ],
  "extraDependencies": [
    "manifest.json",
    "node_modules/@webcomponents/webcomponentsjs/**",
    "push-manifest.json"
  ],
  "builds": [
    {
      "name": "es6-bundled",
      "browserCapabilities": [
        "es2015"
      ],
      "js": {
        "compile": false,
        "minify": true,
        "transformModulesToAmd": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      },
      "bundle": true,
      "addServiceWorker": true
    }
  ],
  "moduleResolution": "node",
  "npm": true
}
```

I'm not sure where to go from here, after having spent the last two days poring through all the changes I've made since my last working build and trying every possible polymer.json build configuration. Any suggestions would be greatly appreciated.

**Comment by keanulee** [comment] 2018-09-14 17:29
Can't tell what the issue is, but what about setting the properties/attributes in the Lit template before the element definition is imported?

```html
${ editPatient ? html`
<create-patient id="#createPatient"
    opened
    patientName="${patient.name}"
    patientEmail="${patient.email}"
    patientPhone="${patient.phone}"
    patientAddress="${patient.address}"
    patientDob="${patient.dob.original}"
    image="${patient.image}"
    pid="${patient.__id__}"
    editState="${true}">
</create-patient>
` : null }
```

```js
_onEditPatient(patient) {
  console.log('on edit patient event:', patient);
  this.editPatient = true;
  this.patient = patient;
}
```

**Comment by keanulee** [comment] 2018-09-14 17:30
Could also be because you're importing the same bundle twice - the bundler doesn't handle this well. See #190

**Comment by kr05** [comment] 2018-09-14 17:57
Thanks @keanulee, importing the same bundle twice was the problem. I consolidated the two imports and now it's working flawlessly. Do you have any insight as to why it doesn't like more than one import for each bundle?

**Comment by frankiefu** [comment] 2018-09-14 22:32
Reported issue in tools: https://github.com/Polymer/tools/issues/568
Duplicate of #190

**Closed by frankiefu** 2018-09-14 22:32 UTC

**Comment by usergenic** [comment] 2018-10-01 19:16
FWIW, working on this via https://github.com/Polymer/tools/pull/722 - rollup has some unfortunate assumptions and its own new logic around deduplicating dynamic imports that I'm attempting to get around.  Solution soon.
