### ISSUE TITLE
Migrate to Workbox

### ISSUE THREAD

**Issue by evayde** [Polymer/pwa-starter-kit#211] opened 2018-08-01 14:27 UTC
While there is no hesitation to migrate the whole project to WB here, we could add a guide to the documentation for users who already want to. Any thoughts on this? Or are there already some plans to migrate the whole starter kit any time soon?

**Comment by jsilvermist** [comment] 2018-08-01 16:31
See Polymer/tools#388.

**Comment by JosefJezek** [comment] 2018-08-01 21:52
Duplicate of https://github.com/Polymer/pwa-starter-kit/issues/90

**Closed** 2018-08-01 21:58 UTC
